# Find K Max

### Make a list with random 10 integers

In [1]:
import numpy as np

np.random.seed(10)
l1 = np.random.randint(0,100, size=10)
l1

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

### Bubble : Find Max Function

In [2]:
def FindMax(L):
    M = L[0]; Mi = 0
    for i, v in enumerate(L):
        if M < v:
            M = v
            Mi = i
    return M, Mi


In [3]:
v = FindMax(l1)
v

(93, 5)

# Bit Patterns with Wild Card

### Make Bit Patterns with Wild Card

In [4]:
Lenbpt = 8
charpool = ['1', '0', '?']
bpt = []

for i in range(Lenbpt):
    bpt.append(np.random.choice(charpool))


bpt
    

['?', '1', '?', '1', '1', '1', '?', '1']

In [5]:
def bitstrlist(M, n):
    bstrlist = []
    for i in range(M):
        intstr = (bin(i))[2:]
        intstr = '0'*(n-len(intstr))+intstr
        #print intstr
        bstrlist.append(intstr)
    return bstrlist


bitstrlist(8,3)

['000', '001', '010', '011', '100', '101', '110', '111']

In [6]:
wildidx = []
for i, v in enumerate(bpt):
    if v == '?':
        wildidx.append(i)
print ("Wild char idx: %s"% wildidx)

Max = 2**len(wildidx)

bstrlist = bitstrlist(Max, len(wildidx))
print "bstrlist : %s"% bstrlist

resultlist = []

for ridx, bstr in enumerate(bstrlist):
    idx = 0
    for i in wildidx:
       # print "bpt[%s] = %s : bstr[%s] = %s" % (int(i), bpt[i], int(idx), bstr[idx])
        bpt[i] = bstr[idx]; idx += 1
    resultlist.append(bpt[:])

    
for lst in resultlist:
    print lst


Wild char idx: [0, 2, 6]
bstrlist : ['000', '001', '010', '011', '100', '101', '110', '111']
['0', '1', '0', '1', '1', '1', '0', '1']
['0', '1', '0', '1', '1', '1', '1', '1']
['0', '1', '1', '1', '1', '1', '0', '1']
['0', '1', '1', '1', '1', '1', '1', '1']
['1', '1', '0', '1', '1', '1', '0', '1']
['1', '1', '0', '1', '1', '1', '1', '1']
['1', '1', '1', '1', '1', '1', '0', '1']
['1', '1', '1', '1', '1', '1', '1', '1']


In [7]:
l1 = [1,2,3]
l2 = l1[:]

l1[0] = 9
l2

l1,l2

([9, 2, 3], [1, 2, 3])

## Random Number from Complementary Set

In [8]:
import numpy as np

origin_set = list(range(1,46))

base_set = [2,3,6,7,8,9,10,
            11,13,15,16,17,18,19,20,
            21,22,23,24,25,26,27,28,30, 
            31,32,34,35,36,37,38,39,40, 
            41,42,43,44,45]
c_set = set(origin_set) - set(base_set)

print (sorted(c_set))
result_list = np.random.choice(list(c_set),6, replace=False)

sorted(result_list)

[1, 4, 5, 12, 14, 29, 33]


[1, 4, 5, 12, 14, 29]

# Merge Sort 

### Not Using Library

In [9]:
import math
def merge(ilist):
    length = len(ilist)
    mididx = int(length/2)
    b = [0]*length; i = 0; k = 0;
    j = mididx;
    while (i < mididx) and (j < length):
        if (ilist[i] < ilist[j]):
            b[k] = ilist[i]
            k += 1
            i += 1
        else:
            b[k] = ilist[j]
            k += 1
            j += 1

    if (i < mididx):
        for t in range(i,mididx):
            b[k] = ilist[t]
            k += 1
    elif (j<length):
        for t in range(j,length):
            b[k] = ilist[t]
            k += 1
    ilist[:] = b[:]
    return ilist

        
def mymsort(ilist):
    length = len(ilist)
    if ( length > 3):
        mididx = int(length/2)
        mymsort(ilist[:mididx])
        mymsort(ilist[mididx:])
        ilist = merge(ilist)
    else:
        if (ilist[0] > ilist[1]):
            ilist[0], ilist[1] = ilist[1], ilist[0]
    
    return
    

ilist = np.random.randint(1,100, 8)
print (ilist)
mymsort(ilist)
print (ilist)


[50 52 55 78 70 14 26 14]
[14 14 26 50 52 55 70 78]


# Quick Sort

In [3]:
import numpy as np 

def qpartition(ilist, left, right):
    pivot = left
    l = pivot + 1
    h = right
   
    while (l < h):
        while ( l <= right and ilist[pivot] >= ilist[l] ):
            l += 1

        while ( h > left and ilist[pivot] <= ilist[h] ):
            h -= 1

        if (l < h):
            ilist[l], ilist[h] = ilist[h], ilist[l]
 

    ilist[left], ilist[h] = ilist[h], ilist[left]
    print ('swapped ilist', ilist, 'Pivot : %d' % (ilist[h]))
    return h


def qsort(ilist, left, right):
    
    if (left < right):
        q = qpartition(ilist, left, right)
        qsort(ilist, left, q-1)
        qsort(ilist, q+1, right)
    return ilist


ilist = np.random.randint(0,100,10)
#ilist = [76, 42, 38, 70, 5, 4, 99,20]
#ilist = [70, 38, 42]
ilist = [25, 15, 10, 20, 30, 40, 24]
print ('Unsorted list', ilist)
sortedlist = qsort(ilist, 0, len(ilist)-1)
print ('Sorted list', sortedlist)


Unsorted list [25, 15, 10, 20, 30, 40, 24]
swapped ilist [24, 15, 10, 20, 25, 40, 30] Pivot : 25
swapped ilist [20, 15, 10, 24, 25, 40, 30] Pivot : 24
swapped ilist [10, 15, 20, 24, 25, 40, 30] Pivot : 20
swapped ilist [15, 10, 20, 24, 25, 40, 30] Pivot : 10
swapped ilist [15, 10, 20, 24, 25, 30, 40] Pivot : 40
Sorted list [15, 10, 20, 24, 25, 30, 40]


# Linked List with Python

In [56]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
    
class LL:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
    
    def __iter__(self):
        self.index = 0
        return self
    
    def next(self):
        p = self.head        
        if ( self.index >= self.size):
            raise StopIteration
        else:
            self.index += 1
            return p
        
    def append(self, data):
        newnode = Node(data)
        if self.head == None:
            self.head = newnode
        
        if self.tail == None:
            self.tail = newnode
        else:
            self.tail.next = newnode
            self.tail = newnode
        self.size += 1
    def traverse(self):
        p = self.head
        while ( p != None):
            print p.data
            p = p.next
        
    def delete(self, data):
        p = self.head
        before = self.head
        while ( p != None):
            if ( p.data == data):
                before.next = p.next
                del(p)
                self.size -= 1
                p = None
            else:
                before = p
                p = p.next 
    
    
LL1 = LL()
LL1.append(10)
LL1.append(15)
LL1.append(20)


LL1.traverse()
LL1.delete(15)
LL1.traverse()

for i in LL1:
    print i.data

10
15
20
10
20
10
10


In [108]:
dict1 = {'k1':[1,2,3], 'k2':[4,5,6], 'k3':[7,8,9]}

dict1['k1']
dict1['k2']
dict1['k3']

for k, v in dict1.items():
    print (k,v)
    
for k in dict1:
    print ('key: %s' %k, 'value: ', dict1[k])
    
searchdict = lambda k, v: v in dict1[k]

print (searchdict('k1', 3))

dict1['k4'] = [9,8,7]

for k in dict1:
    print ('key: %s' %k, 'value: ', dict1[k])



k1 [1, 2, 3]
k2 [4, 5, 6]
k3 [7, 8, 9]
key: k1 value:  [1, 2, 3]
key: k2 value:  [4, 5, 6]
key: k3 value:  [7, 8, 9]
True
key: k1 value:  [1, 2, 3]
key: k2 value:  [4, 5, 6]
key: k3 value:  [7, 8, 9]
key: k4 value:  [9, 8, 7]


# Heap

## Heapify

In [85]:
def heapify(hlist, index, hsize):
    largest_idx = index
    left = (index+1) * 2 - 1
    right = left + 1
    print ('i l r %d %d %d'%(index, left, right))
    if (right < hsize):
        print ('id lgst lval rval %d %d %d %d'%(index, hlist[largest_idx], hlist[left], hlist[right]))
    if ( left < hsize and hlist[largest_idx] < hlist[left]):
        largest_idx = left    
    if ( right < hsize and hlist[largest_idx] < hlist[right]):
        largest_idx = right    
    print ('heapify index-1:%d lgrest %d'% (index-1, largest_idx))
    if ( index != largest_idx ):
        hlist[largest_idx], hlist[index] = hlist[index], hlist[largest_idx]
        heapify(hlist, largest_idx, hsize)
    return



In [87]:
hlist = np.random.randint(0,100,6)
#        0.   1.  2.  3.  4.  5
#        1.   2.  3.  4.  5.  6. 
hlist = [40, 76, 65, 33, 60,  5]

for i in range(int(len(hlist)/2)-1, -1, -1):
    heapify(hlist, i, len(hlist))


print (hlist)

i l r 2 5 6
heapify index-1:1 lgrest 2
i l r 1 3 4
id lgst lval rval 1 76 33 60
heapify index-1:0 lgrest 1
i l r 0 1 2
id lgst lval rval 0 40 76 65
heapify index-1:-1 lgrest 1
i l r 1 3 4
id lgst lval rval 1 40 33 60
heapify index-1:0 lgrest 4
i l r 4 9 10
heapify index-1:3 lgrest 4
[76, 60, 65, 33, 40, 5]


# How do you find the duplicate number on a given integer array? 

In [96]:
given = np.random.randint(0,10,10)
print (given)

[1 2 9 8 3 4 8 2 3 6]


In [93]:
gset = list(set(given))
print (gset)

[0, 1, 2, 5, 6, 7, 8]


In [102]:
for i in range(len(given)):
    for j in range(i+1, len(given)):
        if ( i != j):
            if (given[i] == given[j]):
                print ('dup id val : %d %d %d'%(i,j, given[i]))

dup id val : 1 7 2
dup id val : 3 6 8
dup id val : 4 8 3


# How are duplicate characters found in a string?

In [125]:
import string

charpool = list(string.ascii_uppercase)

rstring = np.random.choice(charpool,20)
print (rstring)


chkbool = {}
for i in range(len(rstring)):
    if (rstring[i] in chkbool):
        print ('dup val', rstring[i])
    else:
        chkbool[rstring[i]] = 1

for k,v in chkbool.items():
    print ('k,v %s %s'% (k, v))
    


['P' 'H' 'H' 'M' 'F' 'G' 'Z' 'Q' 'B' 'B' 'O' 'M' 'W' 'G' 'E' 'I' 'K' 'D'
 'V' 'I']
dup val H
dup val B
dup val M
dup val G
dup val I
k,v P 1
k,v H 1
k,v M 1
k,v F 1
k,v G 1
k,v Z 1
k,v Q 1
k,v B 1
k,v O 1
k,v W 1
k,v E 1
k,v I 1
k,v K 1
k,v D 1
k,v V 1


# How do you count the occurrence of a given character in a string? 

In [137]:
import string
charpool = string.ascii_uppercase

rstring = np.random.choice(list(charpool),30)
print (rstring)

cntdict = {}
for i in charpool:
    cntdict[i] = 0
    
for i in range(len(rstring)):
    cntdict[rstring[i]] += 1
    
for k,v in cntdict.items():
    print (k,v)

['R' 'U' 'U' 'K' 'W' 'C' 'L' 'A' 'D' 'P' 'E' 'L' 'H' 'E' 'A' 'H' 'Q' 'H'
 'R' 'G' 'P' 'S' 'P' 'O' 'R' 'N' 'V' 'E' 'H' 'R']
A 2
B 0
C 1
D 1
E 3
F 0
G 1
H 4
I 0
J 0
K 1
L 2
M 0
N 1
O 1
P 3
Q 1
R 4
S 1
T 0
U 2
V 1
W 1
X 0
Y 0
Z 0
