# Find K Max

### Make a list with random 10 integers

In [1]:
import numpy as np

np.random.seed(10)
l1 = np.random.randint(0,100, size=10)
l1

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

### Bubble : Find Max Function

In [2]:
def FindMax(L):
    M = L[0]; Mi = 0
    for i, v in enumerate(L):
        if M < v:
            M = v
            Mi = i
    return M, Mi


In [3]:
v = FindMax(l1)
v

(93, 5)

# Bit Patterns with Wild Card

### Make Bit Patterns with Wild Card

In [4]:
Lenbpt = 8
charpool = ['1', '0', '?']
bpt = []

for i in range(Lenbpt):
    bpt.append(np.random.choice(charpool))


bpt
    

['?', '1', '?', '1', '1', '1', '?', '1']

In [5]:
def bitstrlist(M, n):
    bstrlist = []
    for i in range(M):
        intstr = (bin(i))[2:]
        intstr = '0'*(n-len(intstr))+intstr
        #print intstr
        bstrlist.append(intstr)
    return bstrlist


bitstrlist(8,3)

['000', '001', '010', '011', '100', '101', '110', '111']

In [6]:
wildidx = []
for i, v in enumerate(bpt):
    if v == '?':
        wildidx.append(i)
print ("Wild char idx: %s"% wildidx)

Max = 2**len(wildidx)

bstrlist = bitstrlist(Max, len(wildidx))
print "bstrlist : %s"% bstrlist

resultlist = []

for ridx, bstr in enumerate(bstrlist):
    idx = 0
    for i in wildidx:
       # print "bpt[%s] = %s : bstr[%s] = %s" % (int(i), bpt[i], int(idx), bstr[idx])
        bpt[i] = bstr[idx]; idx += 1
    resultlist.append(bpt[:])

    
for lst in resultlist:
    print lst


SyntaxError: Missing parentheses in call to 'print'. Did you mean print("bstrlist : %s"% bstrlist)? (<ipython-input-6-6f9492dfbda8>, line 10)

In [ ]:
l1 = [1,2,3]
l2 = l1[:]

l1[0] = 9
l2

l1,l2

## Random Number from Complementary Set

In [ ]:
import numpy as np

origin_set = list(range(1,46))

base_set = [2,3,6,7,8,9,10,
            11,13,15,16,17,18,19,20,
            21,22,23,24,25,26,27,28,30, 
            31,32,34,35,36,37,38,39,40, 
            41,42,43,44,45]
c_set = set(origin_set) - set(base_set)

print (sorted(c_set))
result_list = np.random.choice(list(c_set),6, replace=False)

sorted(result_list)

# Merge Sort 

### Not Using Library

In [34]:
import math
def merge(ilist):
    length = len(ilist)
    mididx = int(length/2)
    b = [0]*length; i = 0; k = 0;
    j = mididx;
    while (i < mididx) and (j < length):
        if (ilist[i] < ilist[j]):
            b[k] = ilist[i]
            k += 1
            i += 1
        else:
            b[k] = ilist[j]
            k += 1
            j += 1

    if (i < mididx):
        for t in range(i,mididx):
            b[k] = ilist[t]
            k += 1
    elif (j<length):
        for t in range(j,length):
            b[k] = ilist[t]
            k += 1
    ilist = b
    return ilist

        
def mymsort(ilist):
    length = len(ilist)
    if ( length > 3):
        mididx = int(length/2)
        mymsort(ilist[:mididx])
        mymsort(ilist[mididx:])
        merge(ilist)
    else:
        if (ilist[0] > ilist[1]):
            ilist[0], ilist[1] = ilist[1], ilist[0]
    
    return
    

ilist = np.random.randint(1,100, 8)
print (ilist)
mymsort(ilist)
print (ilist)


[52 21  6 71 62 17 75  5]
[21 52  6 71 17 62  5 75]
