# Find K Max

### Make a list with random 10 integers

In [1]:
import numpy as np

np.random.seed(10)
l1 = np.random.randint(0,100, size=10)
l1

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

### Bubble : Find Max Function

In [2]:
def FindMax(L):
    M = L[0]; Mi = 0
    for i, v in enumerate(L):
        if M < v:
            M = v
            Mi = i
    return M, Mi


In [3]:
v = FindMax(l1)
v

(93, 5)

# Bit Patterns with Wild Card

### Make Bit Patterns with Wild Card

In [4]:
Lenbpt = 8
charpool = ['1', '0', '?']
bpt = []

for i in range(Lenbpt):
    bpt.append(np.random.choice(charpool))


bpt
    

['?', '1', '?', '1', '1', '1', '?', '1']

In [5]:
def bitstrlist(M, n):
    bstrlist = []
    for i in range(M):
        intstr = (bin(i))[2:]
        intstr = '0'*(n-len(intstr))+intstr
        #print intstr
        bstrlist.append(intstr)
    return bstrlist


bitstrlist(8,3)

['000', '001', '010', '011', '100', '101', '110', '111']

In [6]:
wildidx = []
for i, v in enumerate(bpt):
    if v == '?':
        wildidx.append(i)
print ("Wild char idx: %s"% wildidx)

Max = 2**len(wildidx)

bstrlist = bitstrlist(Max, len(wildidx))
print "bstrlist : %s"% bstrlist

resultlist = []

for ridx, bstr in enumerate(bstrlist):
    idx = 0
    for i in wildidx:
       # print "bpt[%s] = %s : bstr[%s] = %s" % (int(i), bpt[i], int(idx), bstr[idx])
        bpt[i] = bstr[idx]; idx += 1
    resultlist.append(bpt[:])

    
for lst in resultlist:
    print lst


Wild char idx: [0, 2, 6]
bstrlist : ['000', '001', '010', '011', '100', '101', '110', '111']
['0', '1', '0', '1', '1', '1', '0', '1']
['0', '1', '0', '1', '1', '1', '1', '1']
['0', '1', '1', '1', '1', '1', '0', '1']
['0', '1', '1', '1', '1', '1', '1', '1']
['1', '1', '0', '1', '1', '1', '0', '1']
['1', '1', '0', '1', '1', '1', '1', '1']
['1', '1', '1', '1', '1', '1', '0', '1']
['1', '1', '1', '1', '1', '1', '1', '1']


In [7]:
l1 = [1,2,3]
l2 = l1[:]

l1[0] = 9
l2

l1,l2

([9, 2, 3], [1, 2, 3])

## Random Number from Complementary Set

In [8]:
import numpy as np

origin_set = list(range(1,46))

base_set = [2,3,6,7,8,9,10,
            11,13,15,16,17,18,19,20,
            21,22,23,24,25,26,27,28,30, 
            31,32,34,35,36,37,38,39,40, 
            41,42,43,44,45]
c_set = set(origin_set) - set(base_set)

print (sorted(c_set))
result_list = np.random.choice(list(c_set),6, replace=False)

sorted(result_list)

[1, 4, 5, 12, 14, 29, 33]


[1, 4, 5, 12, 14, 29]

# Merge Sort 

### Not Using Library

In [9]:
import math
def merge(ilist):
    length = len(ilist)
    mididx = int(length/2)
    b = [0]*length; i = 0; k = 0;
    j = mididx;
    while (i < mididx) and (j < length):
        if (ilist[i] < ilist[j]):
            b[k] = ilist[i]
            k += 1
            i += 1
        else:
            b[k] = ilist[j]
            k += 1
            j += 1

    if (i < mididx):
        for t in range(i,mididx):
            b[k] = ilist[t]
            k += 1
    elif (j<length):
        for t in range(j,length):
            b[k] = ilist[t]
            k += 1
    ilist[:] = b[:]
    return ilist

        
def mymsort(ilist):
    length = len(ilist)
    if ( length > 3):
        mididx = int(length/2)
        mymsort(ilist[:mididx])
        mymsort(ilist[mididx:])
        ilist = merge(ilist)
    else:
        if (ilist[0] > ilist[1]):
            ilist[0], ilist[1] = ilist[1], ilist[0]
    
    return
    

ilist = np.random.randint(1,100, 8)
print (ilist)
mymsort(ilist)
print (ilist)


[50 52 55 78 70 14 26 14]
[14 14 26 50 52 55 70 78]


# Quick Sort

In [13]:
import numpy as np 

def qpartition(ilist, left, right):
    pivot = left
    l = pivot + 1
    h = right
   
    while (l < h):
        while ( l <= right and ilist[pivot] >= ilist[l] ):
            l += 1

        while ( h > left and ilist[pivot] <= ilist[h] ):
            h -= 1

        if (l < h):
            ilist[l], ilist[h] = ilist[h], ilist[l]
 
    if (l>=h):
        ilist[left], ilist[h] = ilist[h], ilist[left]
    print 'swapped ilist', ilist, 'Pivot : %d' % (ilist[h])
    return h


def qsort(ilist, left, right):
    
    if (left < right):
        q = qpartition(ilist, left, right)
        qsort(ilist, left, q-1)
        qsort(ilist, q+1, right)
    return ilist


ilist = np.random.randint(0,100,10)
#ilist = [76, 42, 38, 70, 5, 4, 99,20]
#ilist = [70, 38, 42]

print ('Unsorted list', ilist)
sortedlist = qsort(ilist, 0, len(ilist)-1)
print ('Sorted list', sortedlist)


('Unsorted list', array([37, 37, 91, 78, 71, 81, 69, 76, 95, 67]))
swapped ilist [37 37 91 78 71 81 69 76 95 67] Pivot : 37
swapped ilist [37 37 91 78 71 81 69 76 95 67] Pivot : 37
swapped ilist [37 37 67 78 71 81 69 76 91 95] Pivot : 91
swapped ilist [37 37 67 78 71 81 69 76 91 95] Pivot : 67
swapped ilist [37 37 67 69 71 76 78 81 91 95] Pivot : 78
swapped ilist [37 37 67 69 71 76 78 81 91 95] Pivot : 69
swapped ilist [37 37 67 69 76 71 78 81 91 95] Pivot : 71
('Sorted list', array([37, 37, 67, 69, 76, 71, 78, 81, 91, 95]))


# Linked List with Python

In [56]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
    
class LL:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
    
    def __iter__(self):
        self.index = 0
        return self
    
    def next(self):
        p = self.head        
        if ( self.index >= self.size):
            raise StopIteration
        else:
            self.index += 1
            return p
        
    def append(self, data):
        newnode = Node(data)
        if self.head == None:
            self.head = newnode
        
        if self.tail == None:
            self.tail = newnode
        else:
            self.tail.next = newnode
            self.tail = newnode
        self.size += 1
    def traverse(self):
        p = self.head
        while ( p != None):
            print p.data
            p = p.next
        
    def delete(self, data):
        p = self.head
        before = self.head
        while ( p != None):
            if ( p.data == data):
                before.next = p.next
                del(p)
                self.size -= 1
                p = None
            else:
                before = p
                p = p.next 
    
    
LL1 = LL()
LL1.append(10)
LL1.append(15)
LL1.append(20)


LL1.traverse()
LL1.delete(15)
LL1.traverse()

for i in LL1:
    print i.data

10
15
20
10
20
10
10


In [69]:
dict1 = {'k1':[1,2,3], 'k2':[4,5,6], 'k3':[7,8,9]}

dict1['k1']
dict1['k2']
dict1['k3']

for k, v in dict1.items():
    print k,v
    
for k in dict1:
    print 'key: %s' %k, 'value: ', dict1[k]
    
searchdict = lambda k, v: v in dict1[k]

print searchdict('k1', 3)




k3 [7, 8, 9]
k2 [4, 5, 6]
k1 [1, 2, 3]
key: k3 value:  [7, 8, 9]
key: k2 value:  [4, 5, 6]
key: k1 value:  [1, 2, 3]
True
