# Matrix Sort

In [1]:
import numpy as np


In [2]:
mat = np.random.randint(0, 100, [10,10])
mat

array([[36, 81, 22, 56, 52, 65, 88, 36, 25,  9],
       [45, 46, 57, 35, 78, 72, 31, 39, 64, 26],
       [82, 12, 22, 25, 95, 31, 59, 11, 12, 77],
       [40, 85, 74, 87, 16,  9, 83, 57, 41, 98],
       [92, 11, 21, 99, 23, 79, 14, 90, 64, 32],
       [54, 62, 17, 43, 42, 52, 99, 52, 93, 67],
       [91, 83, 16, 44, 53, 36, 43, 83, 47,  3],
       [34, 49, 66, 39, 25, 72, 29, 32, 31, 16],
       [10, 62, 71, 40, 14, 38, 24, 16, 65, 52],
       [29, 27,  5, 44, 27, 99, 32, 58, 55, 69]])

In [3]:
print ('max num', mat.max())
print ('min num', mat.min())

max num 99
min num 3


In [4]:
def dimsort(list1):
    for i in range(len(list1)):
        for j in range(i,len(list1)):
            if list1[i] < list1[j]:
                list1[i], list1[j] = list1[j], list1[i]


def mergemat(l1, l2):
    len1 = len(l1)
    len2 = len(l2)
    i = j = k = 0
    rst = [0]*(len1+len2)
    if (len1 == 0):
        rst[:] = l2[:]
        return rst
    if (len2 == 0):
        rst[:] = l1[:]
        return rst
      
    while (i < len1 and j < len2):
        if (l1[i] > l2[j]):
            rst[k] = l1[i]
            k += 1; i += 1
        else:
            rst[k] = l2[j]
            k += 1; j += 1
    
    if (i == len1):
        for t in range(j,len2):
            rst[k] = l2[t]
            k += 1
    if (j == len2):
        for t in range(i,len1):
            rst[k] = l1[t]
            k += 1
    return rst

            
for i in range(len(mat)):
    dimsort(mat[i])

print (mat)

numelm = sum(len(mat[i]) for i in range(len(mat)))


rst = []

for i in range(len(mat)):
    rst = mergemat(rst, mat[i])
    
print (rst)



[[88 81 65 56 52 36 36 25 22  9]
 [78 72 64 57 46 45 39 35 31 26]
 [95 82 77 59 31 25 22 12 12 11]
 [98 87 85 83 74 57 41 40 16  9]
 [99 92 90 79 64 32 23 21 14 11]
 [99 93 67 62 54 52 52 43 42 17]
 [91 83 83 53 47 44 43 36 16  3]
 [72 66 49 39 34 32 31 29 25 16]
 [71 65 62 52 40 38 24 16 14 10]
 [99 69 58 55 44 32 29 27 27  5]]
[99, 99, 99, 98, 95, 93, 92, 91, 90, 88, 87, 85, 83, 83, 83, 82, 81, 79, 78, 77, 74, 72, 72, 71, 69, 67, 66, 65, 65, 64, 64, 62, 62, 59, 58, 57, 57, 56, 55, 54, 53, 52, 52, 52, 52, 49, 47, 46, 45, 44, 44, 43, 43, 42, 41, 40, 40, 39, 39, 38, 36, 36, 36, 35, 34, 32, 32, 32, 31, 31, 31, 29, 29, 27, 27, 26, 25, 25, 25, 24, 23, 22, 22, 21, 17, 16, 16, 16, 16, 14, 14, 12, 12, 11, 11, 10, 9, 9, 5, 3]


# BST

In [5]:
g = np.random.randint(0,100, 10)

g

array([ 2, 14, 98, 77, 88, 74, 35, 98, 94, 72])

In [6]:
class node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
    
class BST:
    def __init__(self):
        self.numnode = 0
        self.root = None
        self.size = 0
    
    def addnode(self, n):
        p = self.root
        if ( p == None):
            self.root = n
            BT.size += 1
            return
        while ( p != None):
            if (n.data < p.data):
                if (p.left == None):
                    print ('parent :', p.data, 'left', n.data)
                    p.left = n
                    BT.size += 1
                    break
                else:
                    p = p.left
            else:
                if (p.right == None):
                    print ('parent :', p.data, 'right', n.data)
                    p.right = n
                    BT.size += 1
                    break
                else:
                    p = p.right
                
    def DFS(self, root):
        p = root
        i = 0
        if ( p != None):
            i += 1
            print (p.data, end=' ')
#            print ('go to left')
            BT.DFS(p.left)
#            print ('go to right')
            BT.DFS(p.right)
        else:
            return

        
BT = BST()

n = [] # list of Node

for i in range(len(g)):
    n.append( node(g[i]) )
    BT.addnode(n[i])
print ('BT Size', BT.size)
root = BT.root
BT.DFS(root)
            
        

parent : 2 right 14
parent : 14 right 98
parent : 98 left 77
parent : 77 right 88
parent : 77 left 74
parent : 74 left 35
parent : 98 right 98
parent : 88 right 94
parent : 35 right 72
BT Size 10
2 14 98 77 74 35 72 88 94 98 

# Dict

In [7]:
import string

l1 = np.random.randint(0,100,10)

upperstr = string.ascii_uppercase

charpool = list(upperstr)

def makedict():
    d1 = {}
    for k in range(len(l1)):
        vals = np.random.choice(charpool, 3)
        d1[k] = vals
    return d1

d = makedict()

for k,v in d.items():
    print (k,v)

0 ['S' 'P' 'K']
1 ['H' 'V' 'W']
2 ['D' 'T' 'Z']
3 ['O' 'T' 'V']
4 ['M' 'E' 'D']
5 ['X' 'I' 'C']
6 ['M' 'D' 'L']
7 ['X' 'D' 'S']
8 ['H' 'B' 'Y']
9 ['T' 'L' 'L']


# DLL

In [8]:
class node:
    def __init__(self, data):
        self.data = data
        self.prev = None
        self.next = None
        
class DLL:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
        
    def append(self, n):
        p = self.head
        if (p == None):  # empty DLL
            self.head = n
            self.tail = n
            self.size += 1
            return n.data
        b = p
        while ( p != None):
            if (n.data > p.data): # find position
                b = p
                p = p.next
            else:
                if (b != p):   # insert into middle postion
                    n.next = p
                    n.prev = b
                    b.next = n
                    p.prev = n
                    self.size += 1
                    return
                else:  # insert into the first position 
                    self.head = n
                    n.next = p
                    p.prev = n
                    self.size += 1
                    return
        if ( p == None): # insert into the last position
            b.next = n
            n.prev = b
            self.tail = n
        self.size += 1
        return n.data
    
    def traverse(self):
        p = self.head
        while(p != None):
            print (p.data, end=' ')
            p = p.next
        print ()
        return
    def traverse_reverse(self):
        p = self.tail
        while (p != None):
            print (p.data, end=' ')
            p = p.prev
        print ()
        return
    def search(self, data):
        p = self.head
        while (p != None):
            if (p.data == data):
                return p
            else:
                p = p.next
        return None
    
    def delete(self, p):
        print ('delete', p.data, 'prev', p.prev, 'next', p.next)
        b = p.prev
        n = p.next
        if ( b == None):
            print('head')
            self.head = p.next
            p.next.prev = None
            p.next = p.prev = None
        elif (n == None):
            print('tail')
            self.tail = p.prev
            p.prev.next = None
            p.next = p.prev = None
        else:
            b.next = p.next
            n.prev = p.prev
        del p
        return
        
                

In [9]:
nvals = np.random.randint(0, 100, 20)

nvals = [95, 42, 69, 89, 37, 66, 97, 98, 64, 90, 79, 61, 23, 28, 12, 94, 25,
       38, 52, 36]
n = [] # class node list
DLL1 = DLL()
for i in range(len(nvals)):
    n.append(node(nvals[i]))
    DLL1.append(n[i])
    

DLL1.traverse()
DLL1.traverse_reverse()
p = DLL1.search(12)
print ('found', p.data)
if (p):
    DLL1.delete(p)
print ('DLL Size %d'%DLL1.size, 'length of list', len(nvals))
DLL1.traverse()
DLL1.traverse_reverse()

del n

12 23 25 28 36 37 38 42 52 61 64 66 69 79 89 90 94 95 97 98 
98 97 95 94 90 89 79 69 66 64 61 52 42 38 37 36 28 25 23 12 
found 12
delete 12 prev None next <__main__.node object at 0x10da2a438>
head
DLL Size 20 length of list 20
23 25 28 36 37 38 42 52 61 64 66 69 79 89 90 94 95 97 98 
98 97 95 94 90 89 79 69 66 64 61 52 42 38 37 36 28 25 23 


# Qsort

In [164]:
glist = np.random.randint(0,100,10)
#glist = [25, 15, 10, 20, 30, 40, 24]

def partition(left,right):
    l = left+1
    h = right
    pval = glist[left]
    while (l <= h):
        while (l<=h and glist[l] <= pval):
            l += 1
        while (l<=h and pval <= glist[h]):
            h -= 1
        if (l < h):
            glist[l], glist[h] = glist[h], glist[l]
    glist[left], glist[h] = glist[h], glist[left]
    return  h 

def qsort(left, right):

    if (right-left > 0):
        q = partition(left, right)
        print ('qsort', glist[left:q])
        qsort(left, q-1)
        print ('qsort', glist[q+1:right+1])
        qsort(q+1, right)
    return

    

In [165]:

print (glist)
qsort(0,9)

print (glist)

[52 31 92 79 76 35  5 59 82  4]
qsort [35 31  4  5]
qsort [ 5 31  4]
qsort [4]
qsort [31]
qsort []
qsort [76 79 59 82 92]
qsort [59]
qsort [79 82 92]
qsort []
qsort [82 92]
qsort []
qsort [92]
[ 4  5 31 35 52 59 76 79 82 92]


# MSort

In [195]:
glist = [25, 15, 10, 35, 30, 40, 24]
glist = np.random.randint(0,100, 7)

def merge(left, h, right):
    b = [None]*(right-left+1)
    i = left
    j = h + 1
    k = 0
    while (i <= h and j <= right):
        if ( glist[i] < glist[j]):
            b[k] = glist[i]
            i += 1; k += 1
        else:
            b[k] = glist[j]
            j += 1; k += 1
    if (i > h):
        b[k:] = glist[j:right+1]
    elif (j>right):
        b[k:] = glist[i:h+1]

    glist[left:right+1] = b[:]
    print (glist[left:right+1])
    del b
    return
    
            
    
def msort(left,right):
    h = int((left+right)/2)
    if ( (right-left) > 0 ):
        msort(left, h)
        msort(h+1,right)
        print ('merge into', glist[left:h+1], glist[h+1:right+1])
        merge(left,h,right)
    return


msort(0,6)
print (glist)


merge into [96] [34]
[34 96]
merge into [56] [25]
[25 56]
merge into [34 96] [25 56]
[25 34 56 96]
merge into [49] [28]
[28 49]
merge into [28 49] [32]
[28 32 49]
merge into [25 34 56 96] [28 32 49]
[25 28 32 34 49 56 96]
[25 28 32 34 49 56 96]
