# Matrix Sort

In [1]:
import numpy as np


In [2]:
mat = np.random.randint(0, 100, [10,10])
mat

array([[52, 67, 46, 31, 30, 23, 37, 48, 49, 30],
       [62, 44, 66, 55, 11, 77, 41,  9, 18, 23],
       [43,  7, 74, 78, 10, 52, 34, 76, 76, 72],
       [ 2, 66, 63, 96, 44, 75,  9, 23, 57, 55],
       [53, 70, 82, 61, 89,  0, 66, 59,  8, 47],
       [62, 54, 56, 28, 42, 93, 61, 57, 56, 59],
       [ 3, 76, 94, 42, 19, 90, 12, 50, 17, 68],
       [29, 17, 10, 31, 13, 63,  5,  9, 50, 63],
       [50, 62, 11, 32, 81, 95, 46, 53, 90,  1],
       [57, 90,  6, 51, 34, 78, 68, 36, 44, 54]])

In [38]:
print ('max num', mat.max())
print ('min num', mat.min())

max num 96
min num 0


In [48]:
def dimsort(list1):
    for i in range(len(list1)):
        for j in range(i,len(list1)):
            if list1[i] < list1[j]:
                list1[i], list1[j] = list1[j], list1[i]
    return list1

def mergemat(l1, l2):
    i = j = k = 0
    rst = []

    if (len(l1) == 0):
        rst.extend(l2)
        return rst
    if (len(l2) == 0):
        rst.extend(l1)
        return rst
   
    while (len(l1)>0 and len(l2)>0):
        if (l1[0] < l2[0]):
            rst.append(l2.pop(0))
        else:
            rst.append(l1.pop(0))
            
    if (len(l1)>0):
        rst.extend(l1)
    if (len(l2)>0):
        rst.extend(l2)
    return rst

            
for i in range(len(mat)):
    mat[i] = dimsort(mat[i])

print (mat)

numelm = sum(len(mat[i]) for i in range(len(mat)))
rst = []
for i in range(len(mat)):
    rst = mergemat(rst, list(mat[i]))
    
print (rst)



[[67 52 49 48 46 37 31 30 30 23]
 [77 66 62 55 44 41 23 18 11  9]
 [78 76 76 74 72 52 43 34 10  7]
 [96 75 66 63 57 55 44 23  9  2]
 [89 82 70 66 61 59 53 47  8  0]
 [93 62 61 59 57 56 56 54 42 28]
 [94 90 76 68 50 42 19 17 12  3]
 [63 63 50 31 29 17 13 10  9  5]
 [95 90 81 62 53 50 46 32 11  1]
 [90 78 68 57 54 51 44 36 34  6]]
[96, 95, 94, 93, 90, 90, 90, 89, 82, 81, 78, 78, 77, 76, 76, 76, 75, 74, 72, 70, 68, 68, 67, 66, 66, 66, 63, 63, 63, 62, 62, 62, 61, 61, 59, 59, 57, 57, 57, 56, 56, 55, 55, 54, 54, 53, 53, 52, 52, 51, 50, 50, 50, 49, 48, 47, 46, 46, 44, 44, 44, 43, 42, 42, 41, 37, 36, 34, 34, 32, 31, 31, 30, 30, 29, 28, 23, 23, 23, 19, 18, 17, 17, 13, 12, 11, 11, 10, 10, 9, 9, 9, 8, 7, 6, 5, 3, 2, 1, 0]


# BST

In [5]:
g = np.random.randint(0,100, 10)

g

array([ 2, 14, 98, 77, 88, 74, 35, 98, 94, 72])

In [6]:
class node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
    
class BST:
    def __init__(self):
        self.numnode = 0
        self.root = None
        self.size = 0
    
    def addnode(self, n):
        p = self.root
        if ( p == None):
            self.root = n
            BT.size += 1
            return
        while ( p != None):
            if (n.data < p.data):
                if (p.left == None):
                    print ('parent :', p.data, 'left', n.data)
                    p.left = n
                    BT.size += 1
                    break
                else:
                    p = p.left
            else:
                if (p.right == None):
                    print ('parent :', p.data, 'right', n.data)
                    p.right = n
                    BT.size += 1
                    break
                else:
                    p = p.right
                
    def DFS(self, root):
        p = root
        i = 0
        if ( p != None):
            i += 1
            print (p.data, end=' ')
#            print ('go to left')
            BT.DFS(p.left)
#            print ('go to right')
            BT.DFS(p.right)
        else:
            return

        
BT = BST()

n = [] # list of Node

for i in range(len(g)):
    n.append( node(g[i]) )
    BT.addnode(n[i])
print ('BT Size', BT.size)
root = BT.root
BT.DFS(root)
            
        

parent : 2 right 14
parent : 14 right 98
parent : 98 left 77
parent : 77 right 88
parent : 77 left 74
parent : 74 left 35
parent : 98 right 98
parent : 88 right 94
parent : 35 right 72
BT Size 10
2 14 98 77 74 35 72 88 94 98 

# Dict

In [7]:
import string

l1 = np.random.randint(0,100,10)

upperstr = string.ascii_uppercase

charpool = list(upperstr)

def makedict():
    d1 = {}
    for k in range(len(l1)):
        vals = np.random.choice(charpool, 3)
        d1[k] = vals
    return d1

d = makedict()

for k,v in d.items():
    print (k,v)

0 ['S' 'P' 'K']
1 ['H' 'V' 'W']
2 ['D' 'T' 'Z']
3 ['O' 'T' 'V']
4 ['M' 'E' 'D']
5 ['X' 'I' 'C']
6 ['M' 'D' 'L']
7 ['X' 'D' 'S']
8 ['H' 'B' 'Y']
9 ['T' 'L' 'L']


# DLL

In [64]:
class node:
    def __init__(self, data):
        self.data = data
        self.prev = None
        self.next = None
        
class DLL:
    def __init__(self):
        self.head = None
        self.tail = None
        self.size = 0
        
    def append(self, n):
        p = self.head
        if (p == None):  # empty DLL
            self.head = n
            self.tail = n
            self.size += 1
            return n.data
        b = p
        while ( p != None):
            if (n.data > p.data): # find position
                b = p
                p = p.next
            else:
                if (b != p):   # insert into middle postion
                    n.next = p
                    n.prev = b
                    b.next = n
                    p.prev = n
                    self.size += 1
                    return
                else:  # insert into the first position 
                    self.head = n
                    n.next = p
                    p.prev = n
                    self.size += 1
                    return
        if ( p == None): # insert into the last position
            b.next = n
            n.prev = b
            self.tail = n
        self.size += 1
        return n.data
    
    def traverse(self):
        p = self.head
        while(p != None):
            print (p.data, end=' ')
            p = p.next
        print ()
        return
    def traverse_reverse(self):
        p = self.tail
        while (p != None):
            print (p.data, end=' ')
            p = p.prev
        print ()
        return
    def search(self, data):
        p = self.head
        while (p != None):
            if (p.data == data):
                return p
            else:
                p = p.next
        return None
    
    def delete(self, p):
        print ('delete', p.data, 'prev', p.prev, 'next', p.next)
        b = p.prev
        n = p.next
        if ( b == None):
            print('head')
            self.head = p.next
            p.next.prev = None
            p.next = p.prev = None
        elif (n == None):
            print('tail')
            self.tail = p.prev
            p.prev.next = None
#            p.next = p.prev = None
        else:
            b.next = p.next
            n.prev = p.prev
        del p
        self.size -= 1
        return 
        
                

In [67]:
nvals = np.random.randint(0, 100, 20)

nvals = [95, 42, 69, 89, 37, 66, 97, 98, 64, 90, 79, 61, 23, 28, 12, 94, 25,
       38, 52, 36]
n = [] # class node list
DLL1 = DLL()
for i in range(len(nvals)):
#    n.append(node(nvals[i]))
    DLL1.append(node(nvals[i]))

DLL1.traverse()
DLL1.traverse_reverse()
p = DLL1.search(12)
print ('found', p.data)
if (p):
    t = DLL1.delete(p)
print ('DLL Size %d'%DLL1.size, )



DLL1.traverse()
DLL1.traverse_reverse()

p = DLL1.search(97)
print ('found', p.data)
if (p):
    t = DLL1.delete(p)
print ('DLL Size %d'%DLL1.size, )

DLL1.traverse()
DLL1.traverse_reverse()

del n



12 23 25 28 36 37 38 42 52 61 64 66 69 79 89 90 94 95 97 98 
98 97 95 94 90 89 79 69 66 64 61 52 42 38 37 36 28 25 23 12 
found 12
delete 12 prev None next <__main__.node object at 0x114861a20>
head
DLL Size 19
23 25 28 36 37 38 42 52 61 64 66 69 79 89 90 94 95 97 98 
98 97 95 94 90 89 79 69 66 64 61 52 42 38 37 36 28 25 23 
found 97
delete 97 prev <__main__.node object at 0x114861630> next <__main__.node object at 0x1148619e8>
DLL Size 18
23 25 28 36 37 38 42 52 61 64 66 69 79 89 90 94 95 98 
98 95 94 90 89 79 69 66 64 61 52 42 38 37 36 28 25 23 


# Qsort

In [164]:
glist = np.random.randint(0,100,10)
#glist = [25, 15, 10, 20, 30, 40, 24]

def partition(left,right):
    l = left+1
    h = right
    pval = glist[left]
    while (l <= h):
        while (l<=h and glist[l] <= pval):
            l += 1
        while (l<=h and pval <= glist[h]):
            h -= 1
        if (l < h):
            glist[l], glist[h] = glist[h], glist[l]
    glist[left], glist[h] = glist[h], glist[left]
    return  h 

def qsort(left, right):

    if (right-left > 0):
        q = partition(left, right)
        print ('qsort', glist[left:q])
        qsort(left, q-1)
        print ('qsort', glist[q+1:right+1])
        qsort(q+1, right)
    return

    

In [165]:

print (glist)
qsort(0,9)

print (glist)

[52 31 92 79 76 35  5 59 82  4]
qsort [35 31  4  5]
qsort [ 5 31  4]
qsort [4]
qsort [31]
qsort []
qsort [76 79 59 82 92]
qsort [59]
qsort [79 82 92]
qsort []
qsort [82 92]
qsort []
qsort [92]
[ 4  5 31 35 52 59 76 79 82 92]


# Qsort 2 - Improved 

In [36]:
import numpy as np
def qsort2(array):
    print (array)
    length = len(array)
    if ( length <= 1):
        return array
    else:
        pivot = array[0]
        less = [ l  for l in array if l < pivot]
        greater = [g for g in array if g > pivot]
    return qsort2(less)+[pivot]+qsort2(greater)


In [37]:
glist = np.random.randint(0,100,10)
glist = qsort2(glist)
print (glist)

[30 18 36 44 13 95 51 14 60 17]
[18, 13, 14, 17]
[13, 14, 17]
[]
[14, 17]
[]
[17]
[]
[36, 44, 95, 51, 60]
[]
[44, 95, 51, 60]
[]
[95, 51, 60]
[51, 60]
[]
[60]
[]
[13, 14, 17, 18, 30, 36, 44, 51, 60, 95]


# MSort

In [195]:
glist = [25, 15, 10, 35, 30, 40, 24]
glist = np.random.randint(0,100, 7)

def merge(left, h, right):
    b = [None]*(right-left+1)
    i = left
    j = h + 1
    k = 0
    while (i <= h and j <= right):
        if ( glist[i] < glist[j]):
            b[k] = glist[i]
            i += 1; k += 1
        else:
            b[k] = glist[j]
            j += 1; k += 1
    if (i > h):
        b[k:] = glist[j:right+1]
    elif (j>right):
        b[k:] = glist[i:h+1]

    glist[left:right+1] = b[:]
    print (glist[left:right+1])
    del b
    return
    
            
    
def msort(left,right):
    h = int((left+right)/2)
    if ( (right-left) > 0 ):
        msort(left, h)
        msort(h+1,right)
        print ('merge into', glist[left:h+1], glist[h+1:right+1])
        merge(left,h,right)
    return


msort(0,6)
print (glist)


merge into [96] [34]
[34 96]
merge into [56] [25]
[25 56]
merge into [34 96] [25 56]
[25 34 56 96]
merge into [49] [28]
[28 49]
merge into [28 49] [32]
[28 32 49]
merge into [25 34 56 96] [28 32 49]
[25 28 32 34 49 56 96]
[25 28 32 34 49 56 96]


# Msort2 - Improved

In [75]:
glist = [25, 15, 10, 35, 30, 40, 24]

def merge2(left, right):
    print (left, right, end=' ')
    if (left == None):
        return right
    if (right == None):
        return left
    merged = []
    while( len(left)>0 and len(right) > 0):
        if ( left[0] < right[0]):
            merged.append(left.pop(0))
        else:
            merged.append(right.pop(0))
            
    if (len(left)>0):
        merged.extend(left[:])
    elif ( len(right)>0):
        merged.extend(right[:])
            
    print ('merged', merged)
    return merged

def msort2(array):
    if (len(array) <= 1 or array == None):
        return array
    else:
        mid = int(len(array)/2)
        left = msort2(array[:mid])
        right = msort2(array[mid:])
    return merge2(left,right)

In [76]:
glist = msort2(glist)
print (glist)

[15] [10] merged [10, 15]
[25] [10, 15] merged [10, 15, 25]
[35] [30] merged [30, 35]
[40] [24] merged [24, 40]
[30, 35] [24, 40] merged [24, 30, 35, 40]
[10, 15, 25] [24, 30, 35, 40] merged [10, 15, 24, 25, 30, 35, 40]
[10, 15, 24, 25, 30, 35, 40]


# Bucket Sort 

In [91]:
glist = [25, 15, 10, 35, 30, 40, 24]
glist = np.random.randint(0,100, 50)
def bucketsort(array):
#    bucket = [ [] for _ in array]
    bucket= [ [] for _ in range(10) ]
    for value in array:
        bucket_index = value // 10
        bucket[bucket_index].append(value)

    for l in bucket:
        l.sort()

    return bucket
print ('glist', glist)
bucket = bucketsort(glist)
for bk in bucket:
    print (bk)


glist [ 2 49 32 86 70 22  4  2 58 17 92 17 39 13 98 71 92 27  1 35 38 67 59 27
 13 67  8 15  1 54 90 12 96 73 83 82 20 41 95 44  4 12 32 95 78 53 75 70
 51 15]
[1, 1, 2, 2, 4, 4, 8]
[12, 12, 13, 13, 15, 15, 17, 17]
[20, 22, 27, 27]
[32, 32, 35, 38, 39]
[41, 44, 49]
[51, 53, 54, 58, 59]
[67, 67]
[70, 70, 71, 73, 75, 78]
[82, 83, 86]
[90, 92, 92, 95, 95, 96, 98]


# dict 2

In [103]:
d2 = {}
d2.update({'k1':[1,2,3]})
d2 = dict(a=1)
l1 = [1,2,3]
l1
l1.append(4)
l1
l1.insert(0,9)
l1
l1.insert(10, 99)
l1
l1[5]
l1.insert(-1,999)
l1
l1.remove(99)
l1
l1.insert(0, 9)
print (l1)
i = l1.remove(9)
print (i)
l1
print ('--', [v for v in l1 if v > 90])


[9, 9, 1, 2, 3, 4, 999]
None
-- [999]


# Overlap 

In [128]:
def overlap(l1, r1, l2, r2):
    isoverlap = True
    if (r1[0] < l2[0]): 
        isoverlap = False
    if (r1[1] < l2[1]):
        isoverlap = False

    return isoverlap

x1 = [(19,23), (15,30)]
x2 = [ (15, 20), (25, 50)]

d = overlap(x1[0], x1[1],  x2[0], x2[1])
print (d)


True


# Find Dupint

In [73]:
glist = np.random.randint(0,100,20)

print (glist)
exist = {}

for v in glist:
    if ( v in exist.keys()):
        print ('dup', v)
    else:
        exist[v] = True

print (exist)
print (exist.keys())
print (exist.values())

[90 55 83 74 75 55 64 54 72 40 34 71 74 86 56 89 91 58 91 55]
dup 55
dup 74
dup 91
dup 55
{90: True, 55: True, 83: True, 74: True, 75: True, 64: True, 54: True, 72: True, 40: True, 34: True, 71: True, 86: True, 56: True, 89: True, 91: True, 58: True}
dict_keys([90, 55, 83, 74, 75, 64, 54, 72, 40, 34, 71, 86, 56, 89, 91, 58])
dict_values([True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True])


# L and S 

In [76]:
given = np.random.randint(0,100,10)
print (given)
min = max = given[0]

for v in given:
    if (min > v):
        min = v
    if (max < v):
        max = v
print (min, max)

[31 31 63 99  6 17 95 92 57 61]
6 99


# All Pairs of sum, dup check

In [86]:
given = np.random.randint(0,100,10)
print (given)

sums = [ [None for _ in range(len(given))] for _ in range(len(given)) ]

for i in range(len(given)):
    for j in range(i+1,len(given)):
        sums[i][j] = given[i] + given[j]

dupcheck = {}
for i in range(len(given)):
    for j in range(i+1,len(given)):
        if ( sums[i][j] in dupcheck.keys()):
            print ('dup', i, j, sums[i][j])
        else:
            dupcheck[sums[i][j]] = True

for i in range(len(given)):
        print (sums[i])

[53 46 10 90 98 96 74 91 74 78]
dup 0 8 127
dup 1 4 144
dup 1 8 120
dup 2 8 84
dup 3 8 164
dup 4 8 172
dup 5 8 170
dup 7 8 165
dup 8 9 152
[None, 99, 63, 143, 151, 149, 127, 144, 127, 131]
[None, None, 56, 136, 144, 142, 120, 137, 120, 124]
[None, None, None, 100, 108, 106, 84, 101, 84, 88]
[None, None, None, None, 188, 186, 164, 181, 164, 168]
[None, None, None, None, None, 194, 172, 189, 172, 176]
[None, None, None, None, None, None, 170, 187, 170, 174]
[None, None, None, None, None, None, None, 165, 148, 152]
[None, None, None, None, None, None, None, None, 165, 169]
[None, None, None, None, None, None, None, None, None, 152]
[None, None, None, None, None, None, None, None, None, None]


In [90]:
i = 100

b = bin(i)
print (b)
s = str(b[2:])
s = '0'*(16-len(s))+s
print (s)

0b1100100
0000000001100100
