# Find K Max

### Make a list with random 10 integers

In [1]:
import numpy as np

np.random.seed(10)
l1 = np.random.randint(0,100, size=10)
l1

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

### Bubble : Find Max Function

In [2]:
def FindMax(L):
    M = L[0]; Mi = 0
    for i, v in enumerate(L):
        if M < v:
            M = v
            Mi = i
    return M, Mi


In [3]:
v = FindMax(l1)
v

(93, 5)

# Bit Patterns with Wild Card

### Make Bit Patterns with Wild Card

In [4]:
Lenbpt = 8
charpool = ['1', '0', '?']
bpt = []

for i in range(Lenbpt):
    bpt.append(np.random.choice(charpool))


bpt
    

['?', '1', '?', '1', '1', '1', '?', '1']

In [5]:
def bitstrlist(M, n):
    bstrlist = []
    for i in range(M):
        intstr = (bin(i))[2:]
        intstr = '0'*(n-len(intstr))+intstr
        #print intstr
        bstrlist.append(intstr)
    return bstrlist


bitstrlist(8,3)

['000', '001', '010', '011', '100', '101', '110', '111']

In [6]:
wildidx = []
for i, v in enumerate(bpt):
    if v == '?':
        wildidx.append(i)
print ("Wild char idx: %s"% wildidx)

Max = 2**len(wildidx)

bstrlist = bitstrlist(Max, len(wildidx))
print "bstrlist : %s"% bstrlist

resultlist = []

for ridx, bstr in enumerate(bstrlist):
    idx = 0
    for i in wildidx:
       # print "bpt[%s] = %s : bstr[%s] = %s" % (int(i), bpt[i], int(idx), bstr[idx])
        bpt[i] = bstr[idx]; idx += 1
    resultlist.append(bpt[:])

    
for lst in resultlist:
    print lst


Wild char idx: [0, 2, 6]
bstrlist : ['000', '001', '010', '011', '100', '101', '110', '111']
['0', '1', '0', '1', '1', '1', '0', '1']
['0', '1', '0', '1', '1', '1', '1', '1']
['0', '1', '1', '1', '1', '1', '0', '1']
['0', '1', '1', '1', '1', '1', '1', '1']
['1', '1', '0', '1', '1', '1', '0', '1']
['1', '1', '0', '1', '1', '1', '1', '1']
['1', '1', '1', '1', '1', '1', '0', '1']
['1', '1', '1', '1', '1', '1', '1', '1']


In [7]:
l1 = [1,2,3]
l2 = l1[:]

l1[0] = 9
l2

l1,l2

([9, 2, 3], [1, 2, 3])

## Random Number from Complementary Set

In [8]:
import numpy as np

origin_set = list(range(1,46))

base_set = [2,3,6,7,8,9,10,
            11,13,15,16,17,18,19,20,
            21,22,23,24,25,26,27,28,30, 
            31,32,34,35,36,37,38,39,40, 
            41,42,43,44,45]
c_set = set(origin_set) - set(base_set)

print (sorted(c_set))
result_list = np.random.choice(list(c_set),6, replace=False)

sorted(result_list)

[1, 4, 5, 12, 14, 29, 33]


[1, 4, 5, 12, 14, 29]

# Merge Sort 

### Not Using Library

In [9]:
import math
def merge(ilist):
    length = len(ilist)
    mididx = int(length/2)
    b = [0]*length; i = 0; k = 0;
    j = mididx;
    while (i < mididx) and (j < length):
        if (ilist[i] < ilist[j]):
            b[k] = ilist[i]
            k += 1
            i += 1
        else:
            b[k] = ilist[j]
            k += 1
            j += 1

    if (i < mididx):
        for t in range(i,mididx):
            b[k] = ilist[t]
            k += 1
    elif (j<length):
        for t in range(j,length):
            b[k] = ilist[t]
            k += 1
    ilist[:] = b[:]
    return ilist

        
def mymsort(ilist):
    length = len(ilist)
    if ( length > 3):
        mididx = int(length/2)
        mymsort(ilist[:mididx])
        mymsort(ilist[mididx:])
        ilist = merge(ilist)
    else:
        if (ilist[0] > ilist[1]):
            ilist[0], ilist[1] = ilist[1], ilist[0]
    
    return
    

ilist = np.random.randint(1,100, 8)
print (ilist)
mymsort(ilist)
print (ilist)


[50 52 55 78 70 14 26 14]
[14 14 26 50 52 55 70 78]


# Quick Sort

In [85]:
def quicksort(ilist):

    lenlist = len(ilist)
    print 'input', ilist
    if (lenlist > 1):
        pivot = 0
        l = pivot + 1
        h = len(ilist) - 1
        
        while (l <= h):
            while (l < len(ilist) and ilist[l] <= ilist[pivot]):
                        l += 1
            print 'l:%d'%l
            while (h>0 and ilist[h] >= ilist[pivot]):
                h -= 1
            print 'h:%d'% h
            if ( l < h ):
                ilist[l], ilist[h] = ilist[h], ilist[l] 
                print 'after swap', ilist
        ilist[l-1], ilist[pivot] = ilist[pivot], ilist[l-1]
        pivot = l - 1
        print 'pivot : %d' % pivot
        print 'pivot swapped', ilist
        quicksort(ilist[:pivot])
        quicksort(ilist[pivot+1:])
        print 'returned', ilist
    return ilist

# unsorted = np.random.randint(0,100,10) 
#unsorted = [ 15, 22, 32,  3,  9, 52, 76, 68, 30, 70]
unsorted = [4,3,2,1]

print 'Unsorted list', unsorted
b
sorted = quicksort(unsorted)

print sorted

Unsorted list [4, 3, 2, 1]
input [4, 3, 2, 1]
l:4
h:3
pivot : 3
pivot swapped [1, 3, 2, 4]
input [1, 3, 2]
l:1
h:0
pivot : 0
pivot swapped [1, 3, 2]
input []
input [3, 2]
l:2
h:1
pivot : 1
pivot swapped [2, 3]
input [2]
input []
returned [2, 3]
returned [1, 3, 2]
input []
returned [1, 3, 2, 4]
[1, 3, 2, 4]


In [136]:
import numpy as np 

def qpartition(ilist, left, right):
    print 'input list', ilist[left:right+1]
    length = right-left+1
    pivot = left
    l = pivot + 1
    h = right
    print 'l:%d, h:%d, p:%d' % (l,h,pivot)
   
    while (l < h):
        while ( l < length and ilist[pivot] > ilist[l] ):
            l += 1

        while ( h > 0 and ilist[pivot] < ilist[h] ):
            h -= 1

        if (l < h):
            ilist[l], ilist[h] = ilist[h], ilist[l]
    print 'low : %d, high :%d'% (l,h)
    print 'l>h ilist', ilist
 
    if (l>=h):
        ilist[left], ilist[h] = ilist[h], ilist[left]
    print 'swapped ilist', ilist
    return h


def qsort(ilist, left, right):
    
    if (left < right):
        q = qpartition(ilist, left, right)
        qsort(ilist, left, q-1)
        qsort(ilist, q+1, right)
    return ilist


ilist = np.random.randint(0,100,10)
#ilist = [76, 42, 38, 70, 5, 4, 99,20]
#ilist = [70, 38, 42]

print ('Unsorted list', ilist)
sortedlist = qsort(ilist, 0, len(ilist)-1)
print ('Sorted list', sortedlist)


('Unsorted list', array([14, 73, 71, 38, 49, 22, 97, 47, 31, 46]))
input list [14 73 71 38 49 22 97 47 31 46]
l:1, h:9, p:0
low : 1, high :0
l>h ilist [14 73 71 38 49 22 97 47 31 46]
swapped ilist [14 73 71 38 49 22 97 47 31 46]
input list [73 71 38 49 22 97 47 31 46]
l:2, h:9, p:1
low : 9, high :8
l>h ilist [14 73 71 38 49 22 46 47 31 97]
swapped ilist [14 31 71 38 49 22 46 47 73 97]
input list [31 71 38 49 22 46 47]
l:2, h:7, p:1
low : 3, high :2
l>h ilist [14 31 22 38 49 71 46 47 73 97]
swapped ilist [14 22 31 38 49 71 46 47 73 97]
input list [38 49 71 46 47]
l:4, h:7, p:3
low : 4, high :3
l>h ilist [14 22 31 38 49 71 46 47 73 97]
swapped ilist [14 22 31 38 49 71 46 47 73 97]
input list [49 71 46 47]
l:5, h:7, p:4


KeyboardInterrupt: 