# <font color=red face="Barriecito" size=14> Sort </font>

## Qsort 

In [142]:
import numpy as np
arr1 = np.random.randint(0,100,11)
arr1

array([21, 76, 90, 98, 93, 76, 28, 85, 14, 20, 63])

### Make filter funciton and use to filter built-in function.

In [166]:
def ltpivot(x):
    if x < pivot:
        return True
    return False
def rtpivot(x):
    if x > pivot:
        return True
    return False

pivot = arr1[0]
print list(filter(ltpivot, arr1))
print list(filter(rtpivot, arr1))


[14, 20]
[76, 90, 98, 93, 76, 28, 85, 63]


### Smart Way to use lambda function

In [136]:
def Qsort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[0]
    left = list(filter(lambda x: (x < pivot), arr))
    right = list(filter(lambda x: (x >= pivot), arr))
    if (pivot == right[0]): # get rid of duplication for pivot value
        right.pop(0)

    leftsorted = Qsort(left)
    rightsorted = Qsort(right)
    
    leftsorted.append(pivot)
    return leftsorted+rightsorted

In [137]:
res = Qsort(arr1)

print arr1
print res

[81 33 69 49 67 93 64  4 80 32]
[4, 32, 33, 49, 64, 67, 69, 80, 81, 93]


# Msort

In [164]:
arrm = list(np.random.randint(0,100,10))
arrm

[67, 3, 50, 29, 99, 26, 3, 72, 91, 99]

In [162]:
def Msort(arr):
    if len(arr) <= 1:
        return arr
    left = Msort(arr[:len(arr)/2])
    right = Msort(arr[len(arr)/2:])
    arr = Merge(left, right)
    return arr

def Merge(left, right):
    result = []
    while ( (len(left)>0) and (len(right)>0) ):
        if (left[0] < right[0]):
            result.append(left.pop(0))
        else:
            result.append(right.pop(0))
    if (len(left) == 0):
        result += right
    elif (len(right) == 0):
        result += left
    return result

In [165]:
res = Msort(arrm)
print res

[3, 3, 26, 29, 50, 67, 72, 91, 99, 99]


# <font color=red face="Barriecito" size=14> Array </font> 

## Find the pair with given sum in the array

### (1) Naive Approch with any 2 combinations

In [206]:
arr = np.random.randint(0,10,8)
arr

array([1, 7, 6, 5, 4, 0, 9, 9])

In [187]:
gsum = 8
for i in range(len(arr)):
    for j in range(i+1, len(arr)):
        if arr[i] + arr[j] == gsum:
            print i, j, arr[i], arr[j]
            

1 3 3 5
6 7 4 4


### (2) Smart Way

In [222]:
# Sort First

def Qsort(arr):
    if ( len(arr) <= 1):
        return arr
    pivot = arr[0]
    left = list(filter(lambda x: (x<pivot), arr))
    right = list(filter( lambda x: (x>=pivot), arr))
    if (pivot == right[0]):
        right.pop(0)
        
    left = Qsort(left)
    right = Qsort(right)
    left.append(pivot)
    return left+right

result = Qsort(arr)
print result

gsum = 10
# find the position that less than the given sum value.
for i in range(len(result)-1,0,-1):
    if result[i] < gsum:
        pos = i
        break
print pos

for i in range(pos+1):
    for j in range(i+1, pos+1):
        if result[i] + result[j] == gsum:
            print i, j, result[i], result[j]

[0, 1, 4, 5, 6, 7, 9, 9]
7
1 6 1 9
1 7 1 9
2 4 4 6
